# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-09 16:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import django_pim.models.attribute
import django_pim.models.feature
import django_pim.models.files
import django_pim.models.product
import django_pim.models.product_bundle.bundle_link
import django_pim.models.product_picture
import django_pim.models.product_video
import django_pim.models.real_product
import django_pim.utils.hashed_doc_field_file
import django_pim.utils.hashed_image_field_file

# --- Data payload carried over from the squashed chain ---------------------------------
# Kept: operations that seed a fresh database (default ProductLinkType records, the
# canonical_url / og_image system features). Skipped as no-ops on a fresh database:
# duplicate cleanups (0014, 0060), old_features_sets copy (0017), link_type FK backfill
# (0048), set_default_channel + GLOBAL->BUSINESS_UNIT rescope (0049), file_label_t9n /
# is_seo backfills (0051).

LINK_TYPE_RECORDS = [
    {"pk": 1, "idx": "related", "name_t9n": {"en": "Related Products", "pl": "Powiązane produkty"}, "position": 1},
    {"pk": 2, "idx": "crosssell", "name_t9n": {"en": "Cross-sell", "pl": "Cross-sell"}, "position": 2},
    {"pk": 3, "idx": "upsell", "name_t9n": {"en": "Upsell", "pl": "Upsell"}, "position": 3},
    {"pk": 4, "idx": "navigation", "name_t9n": {"en": "Navigation", "pl": "Nawigacja"}, "position": 4},
]


def create_link_types(apps, schema_editor):
    """Create default link types (PKs match the pre-model enum values)."""
    ProductLinkType = apps.get_model("django_pim", "ProductLinkType")
    for record in LINK_TYPE_RECORDS:
        ProductLinkType.objects.get_or_create(
            pk=record["pk"],
            defaults={"idx": record["idx"], "name_t9n": record["name_t9n"], "position": record["position"]},
        )
    # Explicit-PK inserts leave the sequence behind (postgres only).
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT setval(pg_get_serial_sequence('django_pim_productlinktype', 'id'), "
                "COALESCE((SELECT MAX(id) FROM django_pim_productlinktype), 0) + 1, false)"
            )


def create_canonical_url_system_feature(apps, schema_editor):
    """Create canonical_url system feature if it doesn't exist."""
    Feature = apps.get_model("django_pim", "Feature")
    if not Feature.objects.filter(idx="canonical_url").exists():
        Feature.objects.create(
            idx="canonical_url",
            scope=1,  # SYSTEM
            feature_type=4,  # VARCHAR255_T9N
            name_t9n={"en": "Canonical URL", "pl": "Canonical URL"},
            is_required=False,
            is_visible=False,
            is_filterable=False,
            is_searchable=False,
            is_comparable=False,
            is_for_customization=False,
            exclude_from_inheritance=False,
            has_visual_asset=False,
            is_seo=True,
            display_order=10,
        )


def create_og_image_system_feature(apps, schema_editor):
    """Create og_image system feature if it doesn't exist."""
    Feature = apps.get_model("django_pim", "Feature")
    if not Feature.objects.filter(idx="og_image").exists():
        Feature.objects.create(
            idx="og_image",
            scope=1,  # SYSTEM
            feature_type=3,  # VARCHAR255 (not T9N — image URLs are language-independent)
            name_t9n={"en": "OG Image", "pl": "OG Image"},
            is_required=False,
            is_visible=False,
            is_filterable=False,
            is_searchable=False,
            is_comparable=False,
            is_for_customization=False,
            exclude_from_inheritance=False,
            has_visual_asset=False,
            is_seo=True,
            display_order=10,
        )


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_pim", "0001_initial"),
        ("django_pim", "0002_alter_thumb_unique_together_alter_thumb_image_and_more"),
        ("django_pim", "0003_alter_productcategory_unique_together_and_more"),
        ("django_pim", "0004_productcategory_description_t9n"),
        ("django_pim", "0005_attribute_extension_feature_filter_type"),
        ("django_pim", "0006_alter_feature_filter_type_and_more"),
        ("django_pim", "0007_remove_product_tax_class_delete_producttaxclass"),
        ("django_pim", "0008_featureset_is_default"),
        ("django_pim", "0009_productcategorypicture_position"),
        ("django_pim", "0010_alter_productpicture_unique_together_and_more"),
        ("django_pim", "0011_alter_realproduct_sku_and_more"),
        ("django_pim", "0012_files_filescategory_filesdownloadurl_and_more"),
        ("django_pim", "0013_alter_productcategorypicture_position"),
        ("django_pim", "0014_productincategory_unique_product_category"),
        ("django_pim", "0015_bundlesection_productbundle_and_more"),
        ("django_pim", "0016_productcategory_external_id_and_more"),
        ("django_pim", "0017_rename_features_sets_feature_old_features_sets_and_more"),
        ("django_pim", "0018_alter_feature_feature_type"),
        ("django_pim", "0019_productcategory_extension"),
        ("django_pim", "0020_feature_extra_value_feature_is_for_customization_and_more"),
        ("django_pim", "0021_alter_feature_feature_type"),
        ("django_pim", "0022_productattributecustomimage_productattributeimage"),
        ("django_pim", "0023_remove_productpicture_unique_product_picture_main_and_more"),
        ("django_pim", "0024_alter_productattributeimage_unique_together"),
        ("django_pim", "0025_alter_productattributeimage_product"),
        ("django_pim", "0026_attribute_magento_pk_feature_magento_pk"),
        ("django_pim", "0027_productattributeimage_color_hash_and_more"),
        ("django_pim", "0028_alter_attributemodifier_attribute"),
        ("django_pim", "0029_alter_feature_feature_type_alter_feature_filter_type_and_more"),
        ("django_pim", "0030_attributesgroup_attributemodifier_feature_and_more"),
        ("django_pim", "0031_remove_filescategory_name_filescategory_name_t9n"),
        ("django_pim", "0032_realproduct_kind_of_product"),
        ("django_pim", "0033_video_productvideo_and_more"),
        ("django_pim", "0034_attributepicture_and_more"),
        ("django_pim", "0035_productincategory_updated_at"),
        ("django_pim", "0036_alter_attributemodifier_options_and_more"),
        ("django_pim", "0037_remove_attributemodifier_group_and_more"),
        ("django_pim", "0038_attributemodifier_attribute_coerced_and_more"),
        ("django_pim", "0039_attributemodifier_csv_row_hash"),
        ("django_pim", "0040_attributemodifier_real_product"),
        ("django_pim", "0041_featureset_magento_idx_featureset_magento_pk"),
        ("django_pim", "0042_alter_attribute_options_product_magento_pk"),
        ("django_pim", "0043_attribute_idx_attr_feature_optimized_and_more"),
        ("django_pim", "0044_productattribute_updated_at_realproduct_updated_at"),
        ("django_pim", "0045_productpicture_alt_text_t9n"),
        ("django_pim", "0046_productcustom_source_product"),
        ("django_pim", "0047_admin_api_schema_changes"),
        ("django_pim", "0047_bundlelink_can_change_quantity_bundlelink_is_default_and_more"),
        ("django_pim", "0048_product_link_types"),
        ("django_pim", "0049_channel_inheritance"),
        ("django_pim", "0050_pim_settings_signals"),
        ("django_pim", "0051_files_label_t9n"),
        ("django_pim", "0052_gap_models"),
        ("django_pim", "0053_pimsettings_gaps"),
        ("django_pim", "0054_gap_exemption"),
        ("django_pim", "0055_desc_grounding"),
        ("django_pim", "0056_gaps_skip_default"),
        ("django_pim", "0057_gapcheck_picture_alt"),
        ("django_pim", "0058_gapcheck_picture_min_count"),
        ("django_pim", "0059_gapcheck_category_present"),
        ("django_pim", "0060_productattribute_nulls_not_distinct"),
    ]

    dependencies = [
        ("django_regional", "0001_squashed_0006_country_default_currency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributesGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name_t9n", models.JSONField(default=dict)),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal description / instruction. Used to ground AI workflows when matching (feature-set selection, attribute fill). Not shown on the storefront.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attributes Group",
                "verbose_name_plural": "Attributes Groups",
            },
        ),
        migrations.CreateModel(
            name="BundleSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=64, unique=True)),
                ("name", models.JSONField(blank=True, default=dict, null=True)),
                ("desc", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "section_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Included Products")],
                        default=django_pim.models.product_bundle.bundle_link.SectionTypeEnum["INCLUDED_PRODUCTS"],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "system"), (2, "global"), (3, "business unit")],
                        default=django_pim.models.feature.FeatureScopeEnum["BUSINESS_UNIT"],
                    ),
                ),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("magento_idx", models.CharField(blank=True, max_length=26, null=True, unique=True)),
                ("magento_pk", models.IntegerField(blank=True, null=True)),
                ("name_t9n", models.JSONField(default=dict)),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal description / instruction. Used to ground AI workflows when matching (feature-set selection, attribute fill). Not shown on the storefront.",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_filterable", models.BooleanField(default=False)),
                ("is_searchable", models.BooleanField(default=True)),
                ("is_comparable", models.BooleanField(default=False)),
                ("is_for_customization", models.BooleanField(default=False)),
                (
                    "exclude_from_inheritance",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this feature is never inherited — always independent per channel.",
                    ),
                ),
                (
                    "has_visual_asset",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this feature's attribute values carry associated visual assets (icon, swatch, badge).",
                    ),
                ),
                (
                    "is_seo",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this feature is an SEO metadata field (meta_title, meta_description, etc.).",
                    ),
                ),
                ("extra_value", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "feature_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Bool"),
                            (2, "Decimal"),
                            (3, "Varchar 255"),
                            (4, "Varchar 255 t9n"),
                            (5, "Text"),
                            (6, "Text t9n"),
                            (7, "Select"),
                            (8, "Multiselect"),
                            (9, "Json"),
                            (10, "Datetime"),
                            (11, "Json t9n"),
                            (12, "Temperature"),
                            (13, "Length"),
                            (14, "Mass"),
                        ],
                        default=django_pim.models.feature.FeatureTypeEnum["UNKNOWN"],
                    ),
                ),
                (
                    "frontend_input_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Default"),
                            (1, "Swatch_Visual"),
                            (2, "Swatch_Text"),
                            (3, "dropdown"),
                            (4, "dropdown_with_price"),
                            (5, "palette_color"),
                            (6, "slider"),
                            (7, "boolean"),
                            (8, "radio"),
                        ],
                        default=django_pim.models.feature.FrontendInputTypeEnum["DEFAULT"],
                    ),
                ),
                (
                    "filter_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Default"),
                            (1, "Swatch_Image"),
                            (2, "Swatch_Text"),
                            (3, "Slide"),
                            (4, "Boolean"),
                            (5, "Radio_Text"),
                        ],
                        default=django_pim.models.feature.FilterTypeEnum["DEFAULT"],
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name_plural": "features",
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="FeatureSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=256, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=256)),
                (
                    "desc",
                    models.TextField(blank=True, default="", help_text="Feature Set description for internal use"),
                ),
                ("magento_idx", models.CharField(blank=True, max_length=26, null=True)),
                ("magento_pk", models.IntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "features sets",
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="FilesCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_t9n", models.JSONField(default=dict)),
                ("code", models.CharField(max_length=256)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "File category",
                "verbose_name_plural": "File categories",
                "ordering": ["-db_created"],
            },
        ),
        migrations.CreateModel(
            name="GapDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "check_key",
                    models.CharField(
                        choices=[
                            ("feature_present", "Feature present"),
                            ("feature_min_length", "Feature minimum length"),
                            ("picture_present", "Picture present"),
                            ("picture_min_count", "Picture minimum count"),
                            ("picture_alt_present", "Picture alt text present"),
                            ("category_present", "Category assigned"),
                            ("feature_set_default", "Feature set is default (placeholder)"),
                        ],
                        max_length=32,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("languages", models.JSONField(blank=True, null=True)),
                ("channels", models.JSONField(blank=True, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning")], db_index=True, max_length=16
                    ),
                ),
                ("label_t9n", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "gap definition",
                "verbose_name_plural": "gap definitions",
                "ordering": ["display_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    django_pim.utils.hashed_image_field_file.HashedImageField(
                        editable=False,
                        height_field="height",
                        storage=django_pim.utils.hashed_image_field_file.UniqueFileSystemStorage(),
                        upload_to="image",
                        width_field="width",
                    ),
                ),
                (
                    "sha1",
                    models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, unique=True),
                ),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("original_file_name", models.CharField(blank=True, max_length=256, null=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "pictures",
                "ordering": ["-db_created"],
            },
        ),
        migrations.CreateModel(
            name="PimSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "matrix_signals_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic Matrix read model sync on PIM changes"
                    ),
                ),
                (
                    "gaps_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable automatic quality-gap recompute on PIM changes"
                    ),
                ),
                ("gaps_rules_changed_at", models.DateTimeField(blank=True, null=True)),
                ("gaps_recomputed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gaps_skip_default_featureset",
                    models.BooleanField(
                        default=True,
                        help_text="While a product is on the default (placeholder) feature set, report only the 'assign a real feature set' gap and suppress all other checks.",
                    ),
                ),
            ],
            options={
                "verbose_name": "PIM Settings",
                "verbose_name_plural": "PIM Settings",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_class",
                    models.SmallIntegerField(
                        choices=[
                            (0, "ProductBase"),
                            (1, "ProductSimple"),
                            (2, "ProductConfigurable"),
                            (3, "ProductBundle"),
                            (4, "ProductCustom"),
                        ],
                        db_index=True,
                        default=django_pim.models.product.ProductClassEnum["ProductBase"],
                    ),
                ),
                (
                    "visibility",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Not visible individually"),
                            (2, "Catalog"),
                            (3, "Search"),
                            (4, "Catalog and search"),
                        ],
                        default=django_pim.models.product.ProductVisibilityEnum["UNKNOWN"],
                    ),
                ),
                ("magento_pk", models.IntegerField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("inherit_attributes", models.BooleanField(default=False)),
                ("inherit_descriptions", models.BooleanField(default=False)),
                ("inherit_images", models.BooleanField(default=False)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
                (
                    "gap_worst_severity",
                    models.CharField(
                        blank=True,
                        choices=[("critical", "Critical"), ("warning", "Warning")],
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
                ("gap_count", models.IntegerField(default=0)),
                ("gap_evaluated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_pim.featureset",
                        verbose_name="feature_set",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ProductLinkType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=64, unique=True)),
                ("name_t9n", models.JSONField(default=dict)),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal description / instruction. Used to ground AI workflows when matching (feature-set selection, attribute fill). Not shown on the storefront.",
                    ),
                ),
                ("position", models.IntegerField(default=0)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product Link Type",
                "verbose_name_plural": "Product Link Types",
                "ordering": ["position", "idx"],
            },
        ),
        migrations.CreateModel(
            name="Thumb",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "image",
                    django_pim.utils.hashed_image_field_file.HashedImageField(
                        editable=False,
                        height_field="height",
                        storage=django_pim.utils.hashed_image_field_file.UniqueFileSystemStorage(),
                        upload_to="thumb",
                        width_field="width",
                    ),
                ),
                ("sha1", models.CharField(blank=True, default=None, max_length=40, null=True, unique=True)),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "thumbs",
                "ordering": ["-db_created"],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("is_external", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("youtube", "YouTube"), ("vimeo", "Vimeo"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("video_url", models.URLField(blank=True, max_length=256, null=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "videos",
            },
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
                ("extension", models.JSONField(blank=True, null=True)),
                ("magento_idx", models.CharField(blank=True, max_length=26, null=True)),
                ("magento_pk", models.IntegerField(blank=True, null=True)),
                ("name_t9n", models.JSONField(default=dict)),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal description / instruction. Used to ground AI workflows when matching (feature-set selection, attribute fill). Not shown on the storefront.",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="django_pim.attributesgroup",
                        verbose_name="attributes group",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="django_pim.feature",
                        verbose_name="feature",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "attributes",
                "ordering": ["feature__idx", "idx"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(default="", max_length=128, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("inheritance_enabled", models.BooleanField(default=False)),
                ("default_inheritance_flags", models.JSONField(blank=True, default=list)),
                (
                    "currencies",
                    models.ManyToManyField(
                        blank=True,
                        db_table="django_pim_shop_currencies",
                        related_name="pim_channels",
                        to="django_regional.currency",
                        verbose_name="currencies",
                    ),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pim_default_channels",
                        to="django_regional.currency",
                        verbose_name="default_currency",
                    ),
                ),
                (
                    "default_language",
                    models.ForeignKey(
                        help_text="Język domyślny nazw 'All Store Views' w Adminie Magento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pim_default_channels",
                        to="django_regional.language",
                        verbose_name="default_language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        blank=True,
                        db_table="django_pim_shop_languages",
                        related_name="pim_channels",
                        to="django_regional.language",
                        verbose_name="languages",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "channels",
                "db_table": "django_pim_shop",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="FeatureInFeatureSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.IntegerField(default=500)),
                (
                    "attributes_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feature_in_sets",
                        to="django_pim.attributesgroup",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_in_feature_set",
                        to="django_pim.feature",
                        verbose_name="feature",
                    ),
                ),
                (
                    "feature_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_in_feature_set",
                        to="django_pim.featureset",
                        verbose_name="feature_set",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "features in features sets",
            },
        ),
        migrations.AddField(
            model_name="feature",
            name="features_sets",
            field=models.ManyToManyField(
                blank=True,
                related_name="features",
                through="django_pim.FeatureInFeatureSet",
                to="django_pim.featureset",
                verbose_name="features_sets",
            ),
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    django_pim.utils.hashed_doc_field_file.HashedFileField(
                        editable=False,
                        storage=django_pim.utils.hashed_doc_field_file.UniqueFileSystemStorage(),
                        upload_to="files",
                    ),
                ),
                (
                    "sha1",
                    models.CharField(blank=True, db_index=True, default=None, max_length=40, null=True, unique=True),
                ),
                ("original_file_name", models.CharField(blank=True, max_length=256, null=True)),
                ("file_label", models.CharField(blank=True, max_length=256, null=True)),
                ("file_label_t9n", models.JSONField(blank=True, default=dict)),
                ("weight", models.CharField(blank=True, max_length=20, null=True)),
                ("file_path", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "file_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Undefined File Type"),
                            (1, "Picture File Type"),
                            (2, "PDF File Type"),
                            (3, "Document File Type"),
                            (4, "Video File Type"),
                        ],
                        default=django_pim.models.files.FileRoleEnum["UNDEFINED"],
                    ),
                ),
                ("codec", models.CharField(blank=True, max_length=20, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                (
                    "file_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_file_category",
                        to="django_pim.filescategory",
                        verbose_name="product_file_category",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-db_created"],
            },
        ),
        migrations.CreateModel(
            name="FilesDownloadUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(db_index=True, max_length=384, unique=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_downloads_urls",
                        to="django_pim.files",
                        verbose_name="doc_downloads_urls",
                    ),
                ),
            ],
            options={
                "verbose_name": "File downloads urls",
                "verbose_name_plural": "File downloads urls",
                "ordering": ["url"],
            },
        ),
        migrations.CreateModel(
            name="AttributePicture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pictures", to="django_pim.attribute"
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="django_pim.picture",
                        verbose_name="picture",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "attributes pictures",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="PictureDownloadUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(db_index=True, max_length=384, unique=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads_urls",
                        to="django_pim.picture",
                        verbose_name="picture",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pictures downloads urls",
                "ordering": ["url"],
            },
        ),
        migrations.CreateModel(
            name="ProductBundle",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products bundle",
            },
            bases=("django_pim.product",),
        ),
        migrations.CreateModel(
            name="ProductConfigurable",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products configurable",
            },
            bases=("django_pim.product",),
        ),
        migrations.CreateModel(
            name="ProductCustom",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products custom",
            },
            bases=("django_pim.product",),
        ),
        migrations.CreateModel(
            name="ProductSimple",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_pim.product",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "products simple",
            },
            bases=("django_pim.product",),
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="django_pim.channel",
                verbose_name="shop",
            ),
        ),
        migrations.CreateModel(
            name="GapFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("channel_idx", models.CharField(max_length=128)),
                ("language", models.CharField(blank=True, db_index=True, max_length=8, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning")], db_index=True, max_length=16
                    ),
                ),
                ("inherited", models.BooleanField(db_index=True, default=False)),
                ("source_channel", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="django_pim.gapdefinition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_findings",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "gap finding",
                "verbose_name_plural": "gap findings",
            },
        ),
        migrations.CreateModel(
            name="GapExemption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("language", models.CharField(blank=True, max_length=8, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemptions",
                        to="django_pim.gapdefinition",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_exemptions",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "gap exemption",
                "verbose_name_plural": "gap exemptions",
            },
        ),
        migrations.CreateModel(
            name="BundleLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=1)),
                ("can_change_quantity", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_section",
                        to="django_pim.bundlesection",
                        verbose_name="Bundle Sections",
                    ),
                ),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundle_sub_links",
                        to="django_pim.product",
                        verbose_name="subproduct_bundle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "bundle links",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_decimal", models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("overridden_langs", models.JSONField(blank=True, default=list)),
                ("value_txt", models.TextField(blank=True, null=True)),
                ("value_txt_t9n", models.JSONField(blank=True, null=True)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_attributes",
                        to="django_pim.attribute",
                        verbose_name="attribute",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_attributes",
                        to="django_pim.feature",
                        verbose_name="feature",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_attributes",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products attributes",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ConfigurableLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurable_links",
                        to="django_pim.product",
                        verbose_name="subproduct",
                    ),
                ),
                (
                    "subproduct_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurable_links",
                        to="django_pim.productattribute",
                        verbose_name="subproduct_attribute",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "configurable links",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeCustomImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attributes",
                    models.ManyToManyField(related_name="product_attribute_custom_attr", to="django_pim.attribute"),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_custom_picture",
                        to="django_pim.picture",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_custom",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Custom Image with Attributes",
                "verbose_name_plural": "Product Custom Images with Attributes",
                "ordering": ["product"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_picture",
                        to="django_pim.attribute",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_picture",
                        to="django_pim.picture",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attribute_images",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Attribute Image",
                "verbose_name_plural": "Product Attribute Images",
                "ordering": ["product"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idx", models.CharField(max_length=128)),
                ("external_id", models.CharField(blank=True, max_length=128, null=True)),
                ("url_key_t9n", models.JSONField(blank=True, default=dict)),
                ("name_t9n", models.JSONField(default=dict)),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal description / instruction. Used to ground AI workflows when matching (feature-set selection, attribute fill). Not shown on the storefront.",
                    ),
                ),
                ("description_t9n", models.JSONField(default=dict)),
                ("meta_title_t9n", models.JSONField(default=dict)),
                ("meta_description_t9n", models.JSONField(default=dict)),
                ("canonical_url_t9n", models.JSONField(blank=True, default=dict)),
                ("image_url", models.CharField(blank=True, default="", max_length=512)),
                ("og_image_url", models.CharField(blank=True, default="", max_length=512)),
                ("noindex", models.BooleanField(default=False)),
                ("nofollow", models.BooleanField(default=False)),
                ("tree_deep", models.IntegerField(blank=True, db_index=True)),
                ("position", models.IntegerField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("is_in_menu", models.BooleanField(default=False)),
                ("rich_content", models.JSONField(blank=True, null=True)),
                ("extension", models.JSONField(blank=True, null=True)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="django_pim.productcategory",
                        verbose_name="parent_category",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_categories",
                        to="django_pim.channel",
                        verbose_name="shop",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products categories",
                "ordering": ["idx"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryPicture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "picture_role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown Role Picture"),
                            (1, "Main Product Picture"),
                            (2, "General Product Picture"),
                            (3, "Variant Picture"),
                            (4, "Another Angle Picture"),
                        ],
                        default=django_pim.models.product_picture.PictureRoleEnum["UNKNOWN"],
                    ),
                ),
                ("position", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="django_pim.picture",
                        verbose_name="picture",
                    ),
                ),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="django_pim.productcategory",
                        verbose_name="product_category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product category pictures",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_inherited", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="django_pim.files",
                        verbose_name="file",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product File",
                "verbose_name_plural": "Product Files",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductInCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.IntegerField(blank=True, default=0, null=True)),
                ("updated_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_in_category",
                        to="django_pim.productcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_in_category",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products in categories",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="django_pim.ProductInCategory",
                to="django_pim.productcategory",
                verbose_name="categories",
            ),
        ),
        migrations.CreateModel(
            name="ProductLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.IntegerField(blank=True, default=1)),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
                (
                    "linked_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_products_links",
                        to="django_pim.product",
                        verbose_name="linked_product",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "link_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="django_pim.productlinktype",
                        verbose_name="link type",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products links",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductLinkToFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_pim.feature")),
                ("link", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="django_pim.productlink")),
            ],
        ),
        migrations.CreateModel(
            name="ProductPicture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "picture_role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Unknown Role Picture"),
                            (1, "Main Product Picture"),
                            (2, "General Product Picture"),
                            (3, "Variant Picture"),
                            (4, "Another Angle Picture"),
                        ],
                        default=django_pim.models.product_picture.PictureRoleEnum["UNKNOWN"],
                    ),
                ),
                ("position", models.IntegerField(blank=True, default=0)),
                ("alt_text_t9n", models.JSONField(blank=True, default=dict)),
                ("is_inherited", models.BooleanField(default=False)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_pictures",
                        to="django_regional.language",
                        verbose_name="language",
                    ),
                ),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_pim.picture",
                        verbose_name="picture",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products pictures",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price_brutto", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("special_price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("special_price_from", models.DateTimeField(blank=True, null=True)),
                ("special_price_to", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="django_regional.currency",
                        verbose_name="currency",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products prices",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RealProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=128)),
                ("ean", models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                (
                    "kind_of_product",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Product Physical"), (1, "Product Virtual")],
                        default=django_pim.models.real_product.KindOfProductEnum["ProductPhysical"],
                    ),
                ),
                ("weight", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("width", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("height", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("deep", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "real products",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        django.db.models.functions.text.Lower("sku"), models.F("id"), name="idx_realproduct_sku_lower"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("sku"), name="unique_real_product_sku"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="real_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="django_pim.realproduct",
                verbose_name="real_product",
            ),
        ),
        migrations.CreateModel(
            name="AttributeModifier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.FloatField()),
                (
                    "modifier_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "unknown"),
                            (2, "value"),
                            (3, "exclude"),
                            (4, "color_hash_intersection"),
                            (5, "default"),
                            (6, "coerce"),
                        ],
                        default=django_pim.models.attribute.AttributeModifierTypeEnum["UNKNOWN"],
                    ),
                ),
                (
                    "value_modifier",
                    models.DecimalField(blank=True, decimal_places=12, default=0, max_digits=64, null=True),
                ),
                ("csv_row_hash", models.CharField(blank=True, max_length=3000, null=True)),
                (
                    "attribute_coerced",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes_coerced",
                        to="django_pim.attribute",
                        verbose_name="Coerced Attribute",
                    ),
                ),
                (
                    "attribute_modified",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes_modified",
                        to="django_pim.attribute",
                        verbose_name="Modified/Excluded Attribute",
                    ),
                ),
                (
                    "attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attributes_modifier_custom",
                        to="django_pim.attribute",
                        verbose_name="Added attributes to custom",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups_modifier_custom",
                        to="django_pim.attributesgroup",
                        verbose_name="Added group to custom",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_modifier_custom",
                        to="django_pim.feature",
                        verbose_name="Added feature to custom",
                    ),
                ),
                (
                    "feature_modified",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_modified",
                        to="django_pim.feature",
                        verbose_name="Modified/Excluded Feature",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_modifier_custom",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "real_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_product_modifier_custom",
                        to="django_pim.realproduct",
                        verbose_name="real product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "attribute modifiers",
                "ordering": ["feature_modified"],
            },
        ),
        migrations.CreateModel(
            name="PictureThumb",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("width", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "transform_method",
                    models.CharField(
                        choices=[
                            ("resize ratio, white", "Resize ratio safe, white bg"),
                            ("resize ratio, black", "Resize ratio safe, black bg"),
                            ("resize ratio, pink", "Resize ratio safe, pink bg"),
                            ("resize ratio, transparent", "Resize ratio safe, transparent bg"),
                            ("fill and crop, white", "Fill and crop, white bg"),
                            ("fill and crop, black", "Fill and crop, black bg"),
                            ("fill and crop, pink", "Fill and crop, pink bg"),
                            ("fill and crop, transparent", "Fill and crop, transparent bg"),
                            ("remove background experimental", "Remove background experimental"),
                            ("remove background experimental v2", "Remove background experimental_v2"),
                        ],
                        db_index=True,
                        max_length=34,
                    ),
                ),
                (
                    "out_format",
                    models.CharField(
                        choices=[("png", "png"), ("webp", "webp"), ("jpg", "jpg"), ("gif", "gif")],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picture_thumbs",
                        to="django_pim.picture",
                        verbose_name="picture",
                    ),
                ),
                (
                    "thumb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picture_thumbs",
                        to="django_pim.thumb",
                        verbose_name="thumb",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "picture thumbs",
                "ordering": [],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "video_role",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Unknown Video"), (1, "Main Product Video"), (2, "Variant Video")],
                        default=django_pim.models.product_video.VideoRoleEnum["UNKNOWN"],
                    ),
                ),
                ("position", models.IntegerField(blank=True, default=0)),
                ("is_inherited", models.BooleanField(default=False)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_videos",
                        to="django_regional.language",
                        verbose_name="language",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="django_pim.product",
                        verbose_name="product",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="django_pim.video",
                        verbose_name="video",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "products videos",
                "ordering": [],
            },
        ),
        migrations.AddIndex(
            model_name="attribute",
            index=models.Index(fields=["feature"], include=("id", "idx"), name="idx_attr_feature_optimized"),
        ),
        migrations.AlterUniqueTogether(
            name="attribute",
            unique_together={("feature", "idx"), ("feature", "magento_idx")},
        ),
        migrations.AddConstraint(
            model_name="featureinfeatureset",
            constraint=models.UniqueConstraint(fields=("feature", "feature_set"), name="unique_feature_in_feature_set"),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(fields=["feature_type"], include=("id", "idx"), name="idx_feature_type_optimized"),
        ),
        migrations.AddConstraint(
            model_name="attributepicture",
            constraint=models.UniqueConstraint(fields=("attribute", "picture"), name="unique_attribute_picture"),
        ),
        migrations.AddField(
            model_name="bundlelink",
            name="product_bundle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bundle_links",
                to="django_pim.productbundle",
                verbose_name="product_bundle",
            ),
        ),
        migrations.AddField(
            model_name="configurablelink",
            name="product_configurable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subproduct_links",
                to="django_pim.productconfigurable",
                verbose_name="product_configurable",
            ),
        ),
        migrations.AddField(
            model_name="productcustom",
            name="customization_feature_set",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="django_pim.featureset"
            ),
        ),
        migrations.AddField(
            model_name="productcustom",
            name="source_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Source Simple or Configurable product this custom product is derived from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_products",
                to="django_pim.product",
            ),
        ),
        migrations.AddIndex(
            model_name="gapfinding",
            index=models.Index(fields=["channel_idx", "severity"], name="idx_gapfinding_channel_sev"),
        ),
        migrations.AlterUniqueTogether(
            name="gapfinding",
            unique_together={("product", "definition", "language")},
        ),
        migrations.AddConstraint(
            model_name="gapexemption",
            constraint=models.UniqueConstraint(
                fields=("product", "definition", "language"), name="uniq_gap_exemption", nulls_distinct=False
            ),
        ),
        migrations.AddIndex(
            model_name="productattribute",
            index=models.Index(fields=["attribute", "product"], name="idx_productattribute_optimized"),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "feature", "attribute"), name="uniq_product_feature_attribute", nulls_distinct=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productattributeimage",
            unique_together={("product", "attribute")},
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(fields=("shop", "idx"), name="Products_Categories_unique_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productcategorypicture",
            unique_together={("product_category", "picture")},
        ),
        migrations.AlterUniqueTogether(
            name="productfile",
            unique_together={("product", "file")},
        ),
        migrations.AddConstraint(
            model_name="productincategory",
            constraint=models.UniqueConstraint(fields=("product", "category"), name="unique_product_category"),
        ),
        migrations.AlterUniqueTogether(
            name="productlink",
            unique_together={("product", "linked_product", "link_type")},
        ),
        migrations.AddConstraint(
            model_name="productpicture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("picture_role", django_pim.models.product_picture.PictureRoleEnum["MAIN"])),
                fields=("product", "picture_role", "language"),
                name="unique_product_picture_main",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpicture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("picture_role", django_pim.models.product_picture.PictureRoleEnum["GENERAL"])),
                fields=("product", "picture", "language"),
                name="unique_product_picture_general",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpicture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("picture_role", django_pim.models.product_picture.PictureRoleEnum["ANGLE"])),
                fields=("product", "picture", "language"),
                name="unique_product_picture_angle",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpicture",
            constraint=models.UniqueConstraint(
                condition=models.Q(("picture_role", django_pim.models.product_picture.PictureRoleEnum["VARIANT"])),
                fields=("product", "picture", "language"),
                name="unique_product_picture_variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productprice",
            unique_together={("product", "currency")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["real_product", "id"], name="idx_product_realproduct"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("real_product", "shop")},
        ),
        migrations.AlterUniqueTogether(
            name="picturethumb",
            unique_together={("picture", "thumb", "width", "height", "transform_method", "out_format")},
        ),
        migrations.AddConstraint(
            model_name="productvideo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video_role", django_pim.models.product_video.VideoRoleEnum["MAIN"])),
                fields=("product", "video_role", "language"),
                name="unique_product_video_main",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvideo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video_role", django_pim.models.product_video.VideoRoleEnum["VARIANT"])),
                fields=("product", "video", "language"),
                name="unique_product_video_variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bundlelink",
            unique_together={("product_bundle", "subproduct")},
        ),
        migrations.AlterUniqueTogether(
            name="configurablelink",
            unique_together={("product_configurable", "subproduct_attribute")},
        ),
        migrations.RunPython(create_link_types, migrations.RunPython.noop),
        migrations.RunPython(create_canonical_url_system_feature, migrations.RunPython.noop),
        migrations.RunPython(create_og_image_system_feature, migrations.RunPython.noop),
    ]
