# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-08-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_pim", "0001_squashed_0060_productattribute_nulls_not_distinct"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariantGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Magento swatch label, for admin readability only.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("db_created", models.DateTimeField(auto_now_add=True)),
                ("db_modified", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="The attribute that differentiates members of this group (e.g. weight).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_variant_groups",
                        to="django_pim.feature",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Seed product whose Magento endpoint defined this cross; product-detail serves groups by owner.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_variant_groups",
                        to="django_pim.product",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variant_groups",
                        to="django_pim.channel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariantGroupProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Swatch order, seeded from Attribute.display_order."
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_products",
                        to="django_pim.productvariantgroup",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_group_memberships",
                        to="django_pim.product",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("group", "product")},
            },
        ),
        migrations.AddField(
            model_name="productvariantgroup",
            name="products",
            field=models.ManyToManyField(
                related_name="variant_groups", through="django_pim.ProductVariantGroupProduct", to="django_pim.product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariantgroup",
            constraint=models.UniqueConstraint(
                fields=("shop", "owner", "feature"), name="uniq_variant_group_shop_owner_feature"
            ),
        ),
    ]
