"""
Business logic services for django-pim.

This package contains service layer implementations that handle business logic
separate from models and API views.
"""

from .attribute_service import (
    create_attribute,
    delete_attribute,
    get_attribute_by_composite_key,
    list_attributes,
    list_attributes_for_feature,
    reorder_attributes,
    resolve_attribute_name,
    update_attribute,
)
from .attributes_group_service import (
    create_attributes_group,
    delete_attributes_group,
    get_attributes_group_by_idx,
    list_attributes_groups,
    resolve_attributes_group_name,
    update_attributes_group,
)
from .category_service import (
    create_category,
    delete_category,
    get_category_by_idx,
    get_category_detail,
    list_categories,
    reorder_categories,
    update_category,
)
from .channel_service import get_channel_language, get_default_channel, list_channels, set_default_channel
from .feature_service import (
    build_feature_response,
    create_feature,
    delete_feature,
    get_feature_by_idx,
    list_features,
    resolve_feature_name,
    update_feature,
)
from .feature_set_service import (
    bulk_add_features_to_set,
    bulk_remove_features_from_set,
    create_feature_set,
    delete_feature_set,
    get_feature_set_by_idx,
    get_required_features,
    list_feature_sets,
    list_features_in_feature_set,
    reorder_features_in_set,
    required_feature_idxs_by_set,
    set_feature_required_override,
    update_feature_set,
)
from .files_category_service import (
    create_files_category,
    delete_files_category,
    get_files_category_by_code,
    list_files_categories,
    resolve_files_category_name,
    update_files_category,
)
from .gap_definition_service import (
    create_gap_definition,
    delete_gap_definition,
    get_gap_definition,
    list_gap_definitions,
    update_gap_definition,
)
from .gap_detection_service import detect_for_product
from .gap_exemption_service import create_exemption, delete_exemption, list_exemptions
from .gap_query_service import get_findings_for_products
from .gap_recompute_service import (
    is_full_recompute_running,
    recompute_all,
    recompute_pks,
    recompute_range,
    recompute_rollup_for_products,
    trigger_full_recompute,
)
from .gap_rule_service import (
    apply_severity_change,
    cleanup_rule_findings,
    get_gaps_settings,
    get_gaps_status,
    is_catalog_stale,
    mark_recomputed,
    mark_rules_changed,
    update_gaps_settings,
)
from .inheritance_service import (
    add_product_to_channel,
    copy_translations,
    get_default_product_for,
    materialize_inherited_media,
    materialize_inherited_values,
    propagate_media_to_inheriting,
    propagate_to_inheriting_products,
    toggle_language_override,
    toggle_media_override,
)
from .product_file_service import link_file_to_product, list_product_files, unlink_file_from_product, upload_file
from .product_in_category_service import list_products_in_category, reorder_products_in_category
from .product_link_service import (
    create_product_link,
    delete_product_link,
    get_product_link,
    list_product_links,
    resolve_product_name,
    update_product_link,
)
from .product_link_type_service import (
    create_product_link_type,
    delete_product_link_type,
    get_product_link_type_by_idx,
    list_product_link_types,
    resolve_product_link_type_name,
    update_product_link_type,
)
from .product_picture_service import (
    get_product_picture,
    link_picture_to_product,
    list_product_pictures,
    unlink_picture_from_product,
    update_product_picture,
    upload_picture,
)
from .product_service import (
    build_product_detail_data,
    bulk_update_products,
    create_product,
    delete_product,
    get_product_by_sku,
    get_product_detail,
    list_products,
    update_product,
)
from .product_video_service import (
    create_product_video,
    delete_product_video,
    get_product_video,
    list_product_videos,
    update_product_video,
)

__all__ = [
    "list_channels",
    "get_channel_language",
    "get_default_channel",
    "set_default_channel",
    "detect_for_product",
    "recompute_all",
    "recompute_pks",
    "recompute_range",
    "recompute_rollup_for_products",
    "apply_severity_change",
    "cleanup_rule_findings",
    "is_catalog_stale",
    "mark_recomputed",
    "mark_rules_changed",
    "get_gaps_status",
    "get_gaps_settings",
    "update_gaps_settings",
    "is_full_recompute_running",
    "trigger_full_recompute",
    "list_gap_definitions",
    "get_gap_definition",
    "create_gap_definition",
    "update_gap_definition",
    "delete_gap_definition",
    "get_findings_for_products",
    "list_exemptions",
    "create_exemption",
    "delete_exemption",
    "get_default_product_for",
    "materialize_inherited_values",
    "propagate_to_inheriting_products",
    "copy_translations",
    "add_product_to_channel",
    "toggle_language_override",
    "toggle_media_override",
    "materialize_inherited_media",
    "propagate_media_to_inheriting",
    "list_products",
    "get_product_by_sku",
    "get_product_detail",
    "create_product",
    "update_product",
    "delete_product",
    "build_product_detail_data",
    "bulk_update_products",
    "list_categories",
    "get_category_by_idx",
    "get_category_detail",
    "create_category",
    "update_category",
    "delete_category",
    "reorder_categories",
    "list_features",
    "get_feature_by_idx",
    "resolve_feature_name",
    "create_feature",
    "update_feature",
    "delete_feature",
    "list_feature_sets",
    "get_feature_set_by_idx",
    "list_features_in_feature_set",
    "create_feature_set",
    "update_feature_set",
    "delete_feature_set",
    "bulk_add_features_to_set",
    "bulk_remove_features_from_set",
    "reorder_features_in_set",
    "required_feature_idxs_by_set",
    "set_feature_required_override",
    "get_required_features",
    "list_attributes",
    "get_attribute_by_composite_key",
    "list_attributes_for_feature",
    "resolve_attribute_name",
    "create_attribute",
    "update_attribute",
    "delete_attribute",
    "reorder_attributes",
    "list_attributes_groups",
    "get_attributes_group_by_idx",
    "resolve_attributes_group_name",
    "create_attributes_group",
    "update_attributes_group",
    "delete_attributes_group",
    "list_product_link_types",
    "get_product_link_type_by_idx",
    "resolve_product_link_type_name",
    "create_product_link_type",
    "update_product_link_type",
    "delete_product_link_type",
    "list_product_links",
    "get_product_link",
    "create_product_link",
    "update_product_link",
    "delete_product_link",
    "upload_picture",
    "list_product_pictures",
    "get_product_picture",
    "link_picture_to_product",
    "update_product_picture",
    "unlink_picture_from_product",
    "list_files_categories",
    "get_files_category_by_code",
    "resolve_files_category_name",
    "create_files_category",
    "update_files_category",
    "delete_files_category",
    "upload_file",
    "list_product_files",
    "link_file_to_product",
    "unlink_file_from_product",
    "list_product_videos",
    "get_product_video",
    "create_product_video",
    "update_product_video",
    "delete_product_video",
    "list_products_in_category",
    "reorder_products_in_category",
]
